### ISSUE TITLE
use Symphonia to support other codecs?

### ISSUE THREAD

**Issue by Be-ing** [RustyDAW/creek#1]
Have you considered using [Symphonia](https://github.com/pdeljanov/Symphonia) for supporting compressed codecs?

**Comment by Be-ing** [comment]
Oh I see this already uses Sympohonia to decode WAV. Should other codecs supported by Symphonia Just Work and it's a matter of verifying that they do?

**Comment by BillyDM** [comment]
When I was writing this crate `Symphonia` didn't support streaming very well. I'll see if they now have better support for it.

**Comment by Be-ing** [comment]
Symphonia now describes its FLAC and MP3 decoders as [excellent](https://github.com/pdeljanov/Symphonia#codecs-decoders).
